# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

include:
  - project: "famedly/company/frontend/ci-templates"
    ref: main
    file: "/all.yml"

stages:
  - build
  - test
  - deploy

build_js:
  image: archlinux:latest
  stage: build
  script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S emscripten libxml2 make cmake jq
    - source /etc/profile
    - useradd -m build
    - chown -R build .
    - su -c 'make -C js' build
  artifacts:
    paths:
      - js/Imaging.js
      - js/Imaging.wasm

test_js:
  image: archlinux:latest
  stage: test
  needs:
    - build_js
  script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S chromium dart
    - source /etc/profile
    - useradd -m test
    - chown -R test .
    - su -c 'dart pub get' test
    - su -c 'dart run test -p chrome' test

test_native:
  image: archlinux:latest
  stage: test
  needs: []
  script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S dart binutils gcc make cmake
    - source /etc/profile
    - useradd -m test
    - chown -R test .
    - su -c ./scripts/prepare.sh test
    - su -c 'dart pub get' test
    - su -c 'LD_LIBRARY_PATH=$(pwd)/build dart run test' test
    - su -c 'LD_LIBRARY_PATH=$(pwd)/build dart example/example.dart' test
