// Auto-generated by codegen/autojs.jq — do not edit.
// Copyright (c) 2020 Famedly GmbH
// SPDX-License-Identifier: AGPL-3.0-or-later

import 'dart:js_interop';
import 'dart:typed_data';

@JS('Imaging.init')
external JSPromise<JSAny?> _init();

Future<void> init() async {
  await _init().toDart;
}

// don't change the order!
enum Transform {
  nearest,
  lanczos,
  bilinear,
  bicubic,
  box,
  hamming,
}

@JS('Imaging.Image')
extension type Image._(JSObject _) implements JSObject {
  @JS('fromRGBA')
  external static Image _fromRGBA(int width, int height, JSUint8Array data);

  static Image fromRGBA(int width, int height, List<int> data) {
    final bytes = data is Uint8List ? data : Uint8List.fromList(data);
    return _fromRGBA(width, height, bytes.toJS);
  }

  @JS('loadEncodedPromise')
  external static JSPromise<Image> _loadEncodedPromise(JSUint8Array bytes);

  static Future<Image> loadEncoded(Uint8List bytes) =>
      _loadEncodedPromise(bytes.toJS).toDart;

  external void free();
  external String get mode;
  external int get width;
  external int get height;
  external int get linesize;
  external Image copy();
  external Image blend(Image other, double alpha);
  external Image gaussianBlur(double radius, int passes);
  external Image rotate90();
  external Image rotate180();
  external Image rotate270();
  external Image flipLeftRight();
  external Image flipTopBottom();
  external Image transpose();
  external Image transverse();

  @JS('resample')
  external Image _resample(int width, int height, String mode);

  Image resample(int width, int height, Transform mode) =>
      _resample(width, height, mode.name);

  external String toBlurhash(int xComponents, int yComponents);

  external JSPromise<JSUint8Array> toJpegPromise(int quality);

  Future<Uint8List> toJpeg(int quality) async =>
      (await toJpegPromise(quality).toDart).toDart;
}

