name: "All the sdk specific jobs"

on:
  workflow_call:

jobs:
  pub-dev-dry-run:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      # Setup Dart SDK with JWT token
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true
      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: flutter pub get
      - name: Dry run 
        run: flutter pub publish --dry-run
        
  # Run build js on every PR so we are safe to publish
  build_js:
    runs-on: ubuntu-latest
    # becuase I was lazy to setup the emsc with closure thingy
    container: docker.io/archlinux/archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build JS and WASM
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S emscripten libxml2 make cmake jq zip
          source /etc/profile
          useradd -m build
          chown -R build .
          su -c 'make -C js' build
          zip native_imaging.zip js/Imaging.js js/Imaging.wasm
      - uses: actions/upload-artifact@v4
        with:
          name: native_imaging.zip
          path: native_imaging.zip