name: Publish to pub.dev

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  # Publish using the reusable workflow from dart-lang.
  # Slightly modified to run our prep script first.
  publish:
    name: Publish to pub.dev
    environment: pub.dev
    permissions:
      contents: read
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      # Setup Dart SDK with JWT token
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          flutter-version: '3.13.8'
          channel: stable
          cache: true
      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: flutter pub get
      # has the oidc bits
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46 
      - name: Dry run 
        run: flutter pub publish --dry-run
      # Publishing...
      - name: Publish to pub.dev
        run: flutter pub publish -f

  build_js:
    runs-on: ubuntu-latest
    # becuase I was lazy to setup the emsc with closure thingy
    container: docker.io/archlinux/archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build JS and WASM
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S emscripten libxml2 make cmake jq zip
          source /etc/profile
          useradd -m build
          chown -R build .
          su -c 'make -C js' build
          zip native_imaging.zip js/Imaging.js js/Imaging.wasm
      - uses: actions/upload-artifact@v3
        with:
          name: native_imaging.zip
          path: native_imaging.zip

  create_release:
    needs: [build_js]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: native_imaging.zip
          path: .
      - name: Create release
        run: |
          gh release create ${{ github.ref_name }}
          gh release upload ${{ github.ref_name }} native_imaging.zip --clobber
