name: Publish to pub.dev

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  publish:
    permissions:
      contents: read
      id-token: write
    uses: famedly/frontend-ci-templates/.github/workflows/publish-pub.yml@main

  build_js:
    runs-on: ubuntu-latest
    # becuase I was lazy to setup the emsc with closure thingy
    container: docker.io/archlinux/archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build JS and WASM
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S emscripten libxml2 make cmake jq zip
          source /etc/profile
          useradd -m build
          chown -R build .
          su -c 'make -C js' build
          zip native_imaging.zip js/Imaging.js js/Imaging.wasm
      - uses: actions/upload-artifact@v3
        with:
          name: native_imaging.zip
          path: native_imaging.zip

  create_release:
    needs: [build_js]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: native_imaging.zip
          path: .
      - name: Create release
        run: |
          gh release create ${{ github.ref_name }}
          gh release upload ${{ github.ref_name }} native_imaging.zip --clobber
